- name: install necessary packages for a desktop
  apt:
    name: 
    - ubuntu-gnome-desktop
    - xrdp
    state: latest
    update_cache: true
  tags:
  - desktop

- name: start/enable gdm
  systemd:
    name: gdm
    enabled: true
    state: restarted
  tags:
  - desktop

- name: start/enable xrdp
  systemd:
    name: xrdp
    enabled: true
    state: restarted
  tags:
  - desktop

- name: create user
  user:
    name: "{{ username }}"
    password: "{{ userpass | string | password_hash('sha512')}}"
    shell: /bin/bash
    group: sudo
    state: present
  tags:
  - desktop

- name: template polkit for graphics
  copy:
    src: 45-allow-colord.pkla
    dest: /etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla
  tags:
  - desktop 

- name: reboot server for changes
  reboot:
  tags:
  - desktop
